import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {createDatabase} from '../lib/postgres-adapter.mjs';
import {readFile,writeFile,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHmac,createHash,randomUUID} from 'node:crypto';
import {pathToFileURL} from 'node:url';

test('PostgreSQL purchase workflow, aggregates, rate limiting and session revocation',async()=>{
 const engine=new PGlite();const temp=await mkdtemp(join(tmpdir(),'purchase-test-'));
 try{
  await engine.exec('CREATE ROLE anon; CREATE ROLE authenticated;');
  await engine.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
  const query=async(sql,args=[])=>{if(sql.startsWith('SELECT pg_advisory_xact_lock'))return {rows:[],rowCount:0};let r;try{r=await engine.query(sql,args);}catch(e){console.error(sql,e.message);throw e;}return {rows:r.rows,rowCount:r.affectedRows};};
  const DB=createDatabase(()=>({query,connect:async()=>({query,release(){}})}));
  const secret='test-secret-is-never-used-in-production';const users=[{id:'admin',role:'admin',name:'المدير',code:'TESTADMIN12345'},{id:'S01',role:'site',name:'الموقع الأول',code:'TESTSITEONE12345'},{id:'S02',role:'site',name:'الموقع الثاني',code:'TESTSITETWO12345'}];
  globalThis.__purchaseTestEnv={DB,AUTH_SECRET:secret,BOOTSTRAP_ACCOUNTS:JSON.stringify(users.map(({code,...u})=>({...u,hash:createHmac('sha256',secret).update('CODE:'+code).digest('hex')})))};
  let source=await readFile(new URL('../app/api/purchases/route.js',import.meta.url),'utf8');source=source.replace("import {env} from '@/lib/runtime.mjs';",'const env=globalThis.__purchaseTestEnv;').replace("'@/lib/purchase-domain.mjs'",JSON.stringify(new URL('../lib/purchase-domain.mjs',import.meta.url).href));
  source=source.replace("'@/lib/permissions.mjs'",JSON.stringify(new URL('../lib/permissions.mjs',import.meta.url).href)).replace("'@/lib/passwords.mjs'",JSON.stringify(new URL('../lib/passwords.mjs',import.meta.url).href));
  source=source.replace("'@/lib/branding.mjs'",JSON.stringify(new URL('../lib/branding.mjs',import.meta.url).href));
  let authSource=await readFile(new URL('../lib/purchase-auth.mjs',import.meta.url),'utf8');authSource=authSource.replace("import {env} from './runtime.mjs';",'const env=globalThis.__purchaseTestEnv;');for(const name of ['purchase-domain','permissions','passwords'])authSource=authSource.replace("'./"+name+".mjs'",JSON.stringify(new URL('../lib/'+name+'.mjs',import.meta.url).href));await writeFile(join(temp,'auth.mjs'),authSource);source=source.replace("'@/lib/purchase-auth.mjs'",JSON.stringify(pathToFileURL(join(temp,'auth.mjs')).href));
  await writeFile(join(temp,'route.mjs'),source);const {GET,POST}=await import(pathToFileURL(join(temp,'route.mjs')));
  const origin='https://purchases.test';const post=async(body,cookie='',customOrigin=origin)=>{const response=await POST(new Request(origin+'/api/purchases',{method:'POST',headers:{Origin:customOrigin,'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify(body)}));return {status:response.status,data:await response.json(),cookie:response.headers.get('Set-Cookie')?.split(';')[0]}};
  const get=async(cookie='',q='')=>{const response=await GET(new Request(origin+'/api/purchases'+q,{headers:{Cookie:cookie}}));return {status:response.status,data:await response.json()}};
  const initialSeeds=globalThis.__purchaseTestEnv.BOOTSTRAP_ACCOUNTS;
  globalThis.__purchaseTestEnv.BOOTSTRAP_ACCOUNTS='[]';
  process.env.ADMIN_INITIAL_PASSWORD='first-admin-test-password-2026';
  const bootstrap=await post({op:'login',username:'admin',code:process.env.ADMIN_INITIAL_PASSWORD});assert.equal(bootstrap.status,200);
  const seeded=await DB.prepare('SELECT id,active FROM accounts ORDER BY id').all();assert.equal(seeded.results.length,5);assert.ok(seeded.results.filter(r=>r.id!=='admin').every(r=>r.active===0));
  assert.equal((await post({op:'login',username:'S01',code:process.env.ADMIN_INITIAL_PASSWORD})).status,401);
  await DB.prepare('DELETE FROM accounts').run();await DB.prepare('DELETE FROM login_attempts').run();
  globalThis.__purchaseTestEnv.BOOTSTRAP_ACCOUNTS=initialSeeds;delete process.env.ADMIN_INITIAL_PASSWORD;
  assert.equal((await get()).status,401);assert.equal((await post({op:'login',code:users[0].code},'','https://evil.test')).status,403);assert.equal((await post({op:'login',code:'wrong'})).status,401);
  const admin=(await post({op:'login',code:users[0].code})).cookie;const one=(await post({op:'login',code:users[1].code.toLowerCase()})).cookie;const two=(await post({op:'login',code:users[2].code})).cookie;assert.ok(admin&&one&&two);
  const initialBranding=(await get(admin)).data.branding;assert.equal(initialBranding.revision,0);assert.equal(initialBranding.labels.systemName,'مسار');
  const labels={...initialBranding.labels,systemName:'مشتريات المؤسسة',requestsPage:'احتياجات المواقع',suppliersPage:'شركاء التوريد',usersPage:'الحسابات',syncPage:'نسخة الشيت'};
  assert.equal((await post({op:'settings',labels,revision:0})).status,401);
  assert.equal((await post({op:'settings',labels,revision:0},one)).status,403);
  await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind(JSON.stringify({users:true}), 'S01').run();
  assert.equal((await post({op:'settings',labels,revision:0},one)).status,403);
  await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind('{}', 'S01').run();
  assert.equal((await post({op:'settings',labels:{...labels,systemName:'   '},revision:0},admin)).status,400);
  assert.equal((await post({op:'settings',labels:{...labels,usersPage:'x'.repeat(41)},revision:0},admin)).status,400);
  assert.equal((await post({op:'settings',labels:{...labels,password:'not-a-setting'},revision:0},admin)).status,400);
  const configured=await post({op:'settings',labels,revision:0},admin);assert.equal(configured.status,200);assert.equal(configured.data.branding.revision,1);
  assert.deepEqual((await get(one)).data.branding.labels,labels);assert.equal((await get(admin)).data.branding.revision,1);
  assert.equal((await post({op:'settings',labels:{...labels,systemName:'نسخة قديمة'},revision:0},admin)).status,409);
  assert.equal((await get(admin)).data.branding.labels.systemName,labels.systemName);
  let brandSource=await readFile(new URL('../app/api/branding/route.js',import.meta.url),'utf8');brandSource=brandSource.replace("import {env} from '@/lib/runtime.mjs';",'const env=globalThis.__purchaseTestEnv;').replace("'@/lib/branding.mjs'",JSON.stringify(new URL('../lib/branding.mjs',import.meta.url).href));await writeFile(join(temp,'branding.mjs'),brandSource);const brandingApi=await import(pathToFileURL(join(temp,'branding.mjs')));
  const publicBrand=await brandingApi.GET();assert.equal(publicBrand.status,200);assert.deepEqual(await publicBrand.json(),configured.data.branding);
  const literal={...labels,systemName:'<script>alert(1)</script>'};assert.equal((await post({op:'settings',labels:literal,revision:1},admin)).status,200);assert.equal((await get(admin)).data.branding.labels.systemName,literal.systemName);
  assert.equal((await post({op:'settings',labels,revision:2},admin)).status,200);
  const input={op:'create',id:randomUUID(),requester:'أحمد',priority:'عاجلة',reason:'أعمال الموقع',items:[{name:'اسمنت',spec:'50 كجم',qty:10,unit:'كيس'},{name:'مواسير',spec:'2 بوصة',qty:5,unit:'قطعة'}]};
  assert.equal((await post({...input,items:[{name:'صنف',qty:-1,unit:'قطعة'}]},one)).status,400);
  const created=await post(input,one);assert.equal(created.status,200);let r=created.data.request;assert.equal(r.state,'new');assert.equal((await post(input,one)).data.duplicate,true);assert.equal((await get(one)).data.requests.length,1);assert.equal((await get(two)).data.requests.length,0);assert.equal((await get(two,'?site=S01')).data.requests.length,0);
  // Exercise uploads against the same SQL database and real session authentication.
  const {account}=await import(pathToFileURL(join(temp,'auth.mjs')));const {createInvoiceHandlers,MAX_INVOICE_SIZE}=await import('../lib/invoice-files.mjs');
  const objects=new Map();let puts=0;const bucket={put:async(key,bytes)=>{puts++;objects.set(key,new Uint8Array(bytes));},get:async key=>objects.has(key)?{body:objects.get(key)}:null,delete:async key=>objects.delete(key)};
  const invoiceApi=createInvoiceHandlers({database:DB,bucket,account});
  const jpg=new Uint8Array([255,216,255,224,0,16,74,70,73,70,0,1,255,217]);const fileId=randomUUID();
  const photoGet=(cookie='',query='?requestId='+r.id)=>invoiceApi.GET(new Request(origin+'/api/invoice-files'+query,{headers:{Cookie:cookie}}));
  const photoPost=(cookie=admin,id=fileId,bytes=jpg,fileName='فاتورة.jpg',customOrigin=origin,requestId=r.id)=>{const form=new FormData();form.set('requestId',requestId);form.set('id',id);form.set('file',new Blob([bytes],{type:'image/jpeg'}),fileName);return invoiceApi.POST(new Request(origin+'/api/invoice-files',{method:'POST',headers:{Cookie:cookie,Origin:customOrigin},body:form}));};
  assert.equal((await photoPost(one,randomUUID())).status,403);await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind(JSON.stringify({allSites:true,prices:true,review:true,dispatch:true}), 'S02').run();assert.equal((await photoPost(two,randomUUID())).status,403);await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind('{}', 'S02').run();assert.equal((await photoGet()).status,401);assert.equal((await photoPost('',randomUUID())).status,401);assert.equal((await photoPost(two,randomUUID())).status,403);assert.equal((await photoPost(one,randomUUID(),jpg,'photo.jpg','https://evil.test')).status,403);
  assert.equal((await photoPost(admin,randomUUID(),new TextEncoder().encode('<script>evil</script>'),'fake.jpg')).status,400);
  assert.equal((await photoPost(admin,randomUUID(),new Uint8Array(MAX_INVOICE_SIZE+1))).status,413);assert.equal(puts,0);
  const uploaded=await photoPost();assert.equal(uploaded.status,201);const metadata=(await uploaded.json()).file;assert.equal(metadata.mime,'image/jpeg');assert.equal(metadata.size,jpg.length);assert.equal(metadata.requestId,r.id);assert.equal(metadata.blob_key,undefined);assert.equal(metadata.uploader,undefined);
  assert.equal((await photoPost()).status,200);assert.equal((await photoPost()).status,200);assert.equal(puts,1);assert.equal(objects.size,1);
  const freshApi=createInvoiceHandlers({database:DB,bucket,account});assert.equal((await (await freshApi.GET(new Request(origin+'/api/invoice-files?requestId='+r.id,{headers:{Cookie:admin}}))).json()).files.length,1);
  assert.equal((await photoGet(one)).status,403);assert.equal((await photoGet(one,'?id='+fileId)).status,403);assert.equal((await photoGet(two,'?id='+fileId)).status,403);const photo=await photoGet(admin,'?id='+fileId);assert.equal(photo.status,200);assert.deepEqual(new Uint8Array(await photo.arrayBuffer()),jpg);assert.equal(photo.headers.get('Content-Type'),'image/jpeg');assert.equal(photo.headers.get('Cache-Control'),'private, no-store');assert.equal((await photoGet(admin,'?id='+fileId+'&download=1')).headers.get('Content-Disposition').startsWith('attachment;'),true);
  await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind(JSON.stringify({allSites:true,prices:false}),'S02').run();assert.equal((await photoGet(two)).status,403);await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind('{}','S02').run();
  await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind(JSON.stringify({create:false,receive:false}),'S01').run();assert.equal((await photoPost(one,randomUUID())).status,403);assert.equal((await photoGet(one)).status,403);await DB.prepare('UPDATE accounts SET permissions=? WHERE id=?').bind('{}','S01').run();
  const adminUpload=await photoPost(admin,randomUUID(),jpg,'مدير.jpg');assert.equal(adminUpload.status,201);
  const otherRequestId=randomUUID();await post({...input,id:otherRequestId},two);assert.equal((await photoPost(admin,fileId,jpg,'other.jpg',origin,otherRequestId)).status,409);
  // Unknown SQL acknowledgement must never delete a blob which might already be referenced.
  const uncertainDB={prepare:sql=>{const original=DB.prepare(sql);if(!sql.startsWith('INSERT INTO invoice_files'))return original;return {bind:(...args)=>({run:async()=>{await original.bind(...args).run();throw Error('unknown acknowledgement');}})};}};
  const uncertainApi=createInvoiceHandlers({database:uncertainDB,bucket,account});const retryId=randomUUID();const retryRequest=()=>{const form=new FormData();form.set('requestId',r.id);form.set('id',retryId);form.set('file',new Blob([jpg]),'retry.jpg');return new Request(origin+'/api/invoice-files',{method:'POST',headers:{Cookie:admin,Origin:origin},body:form});};
  assert.equal((await uncertainApi.POST(retryRequest())).status,500);const beforeRetry=puts;assert.equal((await invoiceApi.POST(retryRequest())).status,200);assert.equal(puts,beforeRetry);assert.equal((await photoGet(admin,'?id='+retryId)).status,200);
  for(let n=0;n<17;n++)assert.equal((await photoPost(admin,randomUUID())).status,201);assert.equal((await (await photoGet(admin)).json()).files.length,20);assert.equal((await photoPost(admin,randomUUID())).status,400);
  // Keep later workflow assertions scoped to its original request.
  await DB.prepare('DELETE FROM requests WHERE id=?').bind(otherRequestId).run();
  assert.equal((await post({op:'update',id:r.id,revision:r.revision,action:'review',decision:'reject',note:'مرفوض'},one)).status,403);
  assert.equal((await post({op:'update',id:r.id,revision:r.revision,action:'cancel',note:'إلغاء'},two)).status,403);assert.equal((await post({op:'supplier',name:'مورد',active:true},one)).status,403);
  await post({op:'supplier',id:'supplier1',name:'مورد البناء',phone:'123',email:'test@example.test',notes:'مواد بناء',active:true},admin);
  const update=async(body,cookie=admin)=>post({op:'update',id:r.id,revision:r.revision,...body},cookie);
  assert.equal((await update({action:'review',decision:'approve',supplierId:'supplier1',items:[{approved:11,price:7},{approved:3,price:12}]})).status,400);
  r=(await update({action:'review',decision:'revise',note:'عدل كمية المواسير'})).data.request;assert.equal(r.state,'needs_revision');r=(await update({action:'resubmit',...Object.fromEntries(Object.entries(input).filter(([k])=>!['op','id'].includes(k)))},one)).data.request;assert.equal(r.state,'new');
  r=(await update({action:'review',decision:'approve',supplierId:'supplier1',items:[{approved:8,price:7.25},{approved:3,price:12}],note:'اعتماد جزئي'})).data.request;assert.equal(r.state,'approved');assert.equal((await get(one)).data.requests[0].data.items[0].price,undefined);assert.deepEqual((await get(one)).data.requests[0].data.supplier,{name:'مورد البناء'});assert.equal((await get(one)).data.stats[0].value,undefined);
  assert.equal((await update({action:'dispatch',orderNumber:'PO-1',expected:'2026-02-31'})).status,400);r=(await update({action:'dispatch',orderNumber:'PO-1',expected:'2026-12-01'})).data.request;assert.equal(r.state,'ordered');assert.equal((await update({action:'review',decision:'reject',note:'بعد التوريد'})).status,409);
  assert.equal((await update({action:'receipt',quantities:[1,0],operationId:'admin-receipt'},admin)).status,403);assert.equal((await update({action:'receipt',quantities:[1,0],operationId:'foreign'},two)).status,403);assert.equal((await update({action:'receipt',quantities:[9,0],operationId:'too-many'},one)).status,400);
  const partial={op:'update',id:r.id,revision:r.revision,action:'receipt',quantities:[2,1],note:'دفعة أولى',operationId:'receipt1'};r=(await post(partial,one)).data.request;assert.equal(r.state,'partial');assert.equal((await post(partial,one)).data.duplicate,true);assert.equal((await update({action:'receipt',quantities:[1,0],operationId:'stale',revision:r.revision-1},one)).status,409);
  const final={op:'update',id:r.id,revision:r.revision,action:'receipt',quantities:[6,2],note:'اكتمل',operationId:'receipt2'};r=(await post(final,one)).data.request;assert.equal(r.state,'received');assert.equal((await post(final,one)).data.duplicate,true);const result=await get(admin);assert.equal(result.data.requests[0].received_value,94);assert.equal(result.data.stats[0].value,94);assert.equal(result.data.requests[0].data.receipts.length,2);
  assert.equal(result.data.stats[0].approvedValue,94);assert.equal((await get(admin,'?from=2099-01-01')).data.requests.length,0);assert.equal((await get(admin,'?from=2099-01-01')).data.stats.length,0);assert.equal((await get(admin,'?to='+r.created.slice(0,10))).data.requests.length,1);assert.equal((await get(admin,'?from=2026-12-01&to=2026-01-01')).status,400);assert.equal((await get(one)).data.stats[0].approvedValue,undefined);
  assert.equal((await update({action:'cancel',note:'إلغاء بعد الاستلام'})).status,409);
  assert.equal((await post({op:'site',id:'S01',name:'الموقع الجديد',active:true,newCode:'REPLACECODE1234'},admin)).status,200);assert.equal((await get(one)).status,401);assert.equal((await photoGet(one,'?id='+fileId)).status,401);assert.equal((await post({op:'login',code:users[1].code})).status,401);const changed=await post({op:'login',code:'REPLACECODE1234'});assert.equal(changed.status,200);assert.equal((await get(changed.cookie)).data.requests.length,1);
  assert.equal((await post({op:'site',id:'S01',name:'الموقع الجديد',active:false},admin)).status,200);assert.equal((await get(changed.cookie)).status,401);assert.equal((await post({op:'login',code:'REPLACECODE1234'})).status,401);
  const allFlags={create:false,receive:false,review:false,dispatch:false,suppliers:false,users:false,allSites:false,prices:false};
  assert.equal((await post({op:'user',id:'S02',name:'الموقع الثاني',active:true,permissions:allFlags,newPassword:'StrongPassword123'},admin)).status,200);
  assert.equal((await post({op:'login',code:users[2].code})).status,401);assert.equal((await post({op:'login',username:'S02',code:'strongpassword123'})).status,401);
  let restricted=(await post({op:'login',username:'S02',code:'StrongPassword123'})).cookie;assert.ok(restricted);assert.equal((await post({...input,id:randomUUID()},restricted)).status,403);assert.equal((await get(restricted)).data.users.length,0);
  assert.equal((await post({op:'user',id:'admin',name:'المدير',active:false},admin)).status,400);
  assert.equal((await post({op:'user',id:'S02',name:'الموقع الثاني',active:true,permissions:{...allFlags,allSites:true,review:true}},admin)).status,200);
  assert.equal((await get(restricted)).status,401);restricted=(await post({op:'login',username:'S02',code:'StrongPassword123'})).cookie;const delegated=await get(restricted);assert.equal(delegated.data.requests.length,1);assert.equal(delegated.data.user.permissions.prices,true);assert.equal(delegated.data.requests[0].data.items[0].price,7.25);assert.equal(delegated.data.users.length,0);
  assert.equal((await post({op:'user',id:'S01',name:'موقع',active:true},restricted)).status,403);assert.equal((await post({op:'user',id:'admin',name:'المدير',active:true,newPassword:'NewAdminPassword123',currentPassword:'wrong'},admin)).status,403);
  const renewed=await post({op:'user',id:'admin',name:'المدير',active:true,newPassword:'NewAdminPassword123',currentPassword:users[0].code},admin);assert.equal(renewed.status,200);assert.equal((await get(admin)).status,401);assert.equal((await get(renewed.cookie)).status,200);assert.equal((await post({op:'login',username:'admin',code:users[0].code})).status,401);assert.equal((await post({op:'login',username:'admin',code:'NewAdminPassword123'})).status,200);
  let exportSource=await readFile(new URL('../app/api/sheet-export/route.js',import.meta.url),'utf8');exportSource=exportSource.replace("import {env} from '@/lib/runtime.mjs';",'const env=globalThis.__purchaseTestEnv;').replace("'@/lib/sheet-export.mjs'",JSON.stringify(new URL('../lib/sheet-export.mjs',import.meta.url).href));await writeFile(join(temp,'export.mjs'),exportSource);const exportApi=await import(pathToFileURL(join(temp,'export.mjs')));globalThis.__purchaseTestEnv.SYNC_READ_TOKEN_HASH=createHash('sha256').update('test-sync-token').digest('hex');
  assert.equal((await exportApi.GET(new Request(origin+'/api/sheet-export'))).status,401);const exportResponse=await exportApi.GET(new Request(origin+'/api/sheet-export',{headers:{Authorization:'Bearer test-sync-token'}}));assert.equal(exportResponse.status,200);const exported=await exportResponse.json();assert.equal(exported.lines.length,2);assert.equal(exported.lines[0].length,28);assert.equal(exported.lines[0][1],'PR-000001');assert.equal(exported.lines[0][18],8);assert.equal(exported.lines[0][19],58);assert.equal(exported.nextAfter,null);assert.equal(JSON.stringify(exported).includes('password_hash'),false);
  const ack=await exportApi.POST(new Request(origin+'/api/sheet-export',{method:'POST',headers:{Authorization:'Bearer test-sync-token'},body:JSON.stringify({success:true,lineCount:2,error:''})}));assert.equal(ack.status,200);assert.equal((await get(renewed.cookie)).data.sync.line_count,2);
  const deniedAck=await exportApi.POST(new Request(origin+'/api/sheet-export',{method:'POST',body:JSON.stringify({success:true,lineCount:999,error:''})}));assert.equal(deniedAck.status,401);
  const tampered=admin.slice(0,-1)+(admin.endsWith('a')?'b':'a');assert.equal((await get(tampered)).status,401);
  for(let i=0;i<20;i++)await post({op:'login',code:'wrong'});assert.equal((await post({op:'login',code:'wrong'})).status,429);
 }finally{await engine.close();delete globalThis.__purchaseTestEnv;await rm(temp,{recursive:true,force:true});}
});
