import {can} from './permissions.mjs';
import {fail,required,clean,num} from './purchase-domain.mjs';
export const stockKey=(site,name,spec,unit)=>JSON.stringify([site,name.trim(),spec.trim(),unit.trim()]);
export function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(String(value)))fail('أدخل مبلغًا موجبًا بمنزلتين عشريتين كحد أقصى');const n=Math.round(Number(value)*100);if(!Number.isSafeInteger(n)||n<=0||n>2147483647)fail('المبلغ غير صحيح');return n;}
const validId=x=>{if(typeof x!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(x))fail('معرف العملية غير صحيح');return x;};
function day(x,optional=false){if(optional&&!x)return '';if(typeof x!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x)||!Number.isFinite(Date.parse(x))||new Date(x).toISOString().slice(0,10)!==x)fail('التاريخ غير صحيح');return x;}
const json=(x,status=200)=>Response.json(x,{status,headers:{'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'}});
const error=e=>json({error:e.status?e.message:'تعذر حفظ أو تحميل البيانات'},e.status||500);
export function stockRows(requests,moves){const rows=new Map();function add(site,item,qty,kind){const key=stockKey(site,item.name,item.spec||'',item.unit);const row=rows.get(key)||{key,siteId:site,name:item.name,spec:item.spec||'',unit:item.unit,received:0,added:0,issued:0,balance:0};row[kind]+=qty;row.balance=row.received+row.added-row.issued;rows.set(key,row);}for(const r of requests){const data=typeof r.data==='string'?JSON.parse(r.data):r.data;for(const i of data.items)add(r.site_id,i,Number(i.received||0),'received');}for(const m of moves)add(m.site_id,m,m.qty,m.kind==='in'?'added':'issued');return [...rows.values()].filter(r=>r.received||r.added||r.issued);}
export function createBusinessHandlers({database,account}){
 async function readAccess(request){const a=await account(request);if(a.role!=='admin')fail('هذه الصفحة متاحة للإدارة المصرح لها فقط',403);return a;}
 async function GET(request){try{
 if(new URL(request.url).searchParams.get('view')==='inventory'){
  const a=await account(request);if(a.role!=='site'&&a.role!=='admin')fail('غير مسموح',403);
  const own=a.role==='site';const requests=(await database.prepare("SELECT site_id,data FROM requests WHERE state IN ('approved','ordered','partial','received')"+(own?' AND site_id=?':'')).bind(...(own?[a.id]:[])).all()).results;
  const moves=(await database.prepare('SELECT * FROM stock_moves'+(own?' WHERE site_id=?':'')+' ORDER BY date DESC,created DESC').bind(...(own?[a.id]:[])).all()).results;
  return json({invoices:[],payments:[],approved:[],legacyFiles:[],moves,stock:stockRows(requests,moves)});
 }
 await readAccess(request);const [invoices,payments,moves,requests,files]=await Promise.all([
 database.prepare("SELECT i.*,r.site_id,r.seq,r.data AS request_data,COALESCE((SELECT SUM(amount_cents) FROM invoice_payments p WHERE p.invoice_id=i.id),0) AS paid_cents,(SELECT COUNT(*) FROM invoice_files f WHERE f.invoice_id=i.id) AS file_count FROM supplier_invoices i JOIN requests r ON r.id=i.request_id ORDER BY i.date DESC,i.created DESC").all(),
 database.prepare('SELECT * FROM invoice_payments ORDER BY date DESC,created DESC').all(),database.prepare('SELECT * FROM stock_moves ORDER BY date DESC,created DESC').all(),database.prepare("SELECT * FROM requests WHERE state IN ('approved','ordered','partial','received') ORDER BY seq DESC").all(),database.prepare("SELECT f.id,f.request_id,f.invoice_id,f.filename,f.created,r.site_id,r.seq,r.data AS request_data FROM invoice_files f JOIN requests r ON r.id=f.request_id WHERE f.invoice_id='' ORDER BY f.created DESC").all()]);
 return json({invoices:invoices.results.map(({request_data,...i})=>{const d=JSON.parse(request_data);return {...i,siteName:d.siteName,supplierName:d.supplier?.name||'',remaining_cents:i.total_cents-i.paid_cents};}),payments:payments.results,moves:moves.results,stock:stockRows(requests.results,moves.results),approved:requests.results.map(r=>({...r,data:JSON.parse(r.data)})),legacyFiles:files.results.map(({request_data,...f})=>({...f,siteName:JSON.parse(request_data).siteName}))});}catch(e){return error(e);}}
 async function POST(request){try{if(request.headers.get('Origin')!==new URL(request.url).origin)fail('مصدر الطلب غير صحيح',403);const a=await readAccess(request);if(a.role!=='admin')fail('الحفظ المالي والمخزون متاح لحساب المدير فقط',403);const text=await request.text();if(text.length>20000)fail('الطلب كبير جدًا',413);let input;try{input=JSON.parse(text);}catch{fail('بيانات غير صحيحة');}if(!input||typeof input!=='object')fail('بيانات غير صحيحة');const id=validId(input.id),now=new Date().toISOString();
 if(input.op==='invoice'){
 const prior=await database.prepare('SELECT * FROM supplier_invoices WHERE id=?').bind(id).first();if(prior){if(prior.request_id!==input.requestId||prior.number!==required(input.number,80)||prior.total_cents!==cents(input.total))fail('معرف العملية مستخدم لفاتورة أخرى',409);return json({ok:true,id,duplicate:true});}
 const r=await database.prepare('SELECT * FROM requests WHERE id=?').bind(validId(input.requestId)).first();if(!r||!['ordered','partial','received'].includes(r.state))fail('اختر طلبًا بدأ توريده من المورد');const d=JSON.parse(r.data);if(!d.supplier?.id)fail('المورد غير محدد');
 const number=required(input.number,80),date=day(input.date),due=day(input.due,true);if(due&&due<date)fail('الاستحقاق لا يسبق تاريخ الفاتورة');const total=cents(input.total),notes=clean(input.notes||'',1000);
 const result=await database.prepare('INSERT INTO supplier_invoices (id,request_id,supplier_id,number,date,due,total_cents,notes,created,by) SELECT ?,?,?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM supplier_invoices WHERE supplier_id=? AND number=?) ON CONFLICT(id) DO NOTHING').bind(id,r.id,d.supplier.id,number,date,due,total,notes,now,a.name,d.supplier.id,number).run();if(result.meta.changes!==1)fail('رقم الفاتورة مسجل لهذا المورد بالفعل',409);return json({ok:true,id},201);
 }
 if(input.op==='payment'){
 const invoiceId=validId(input.invoiceId),amount=cents(input.amount),date=day(input.date),method=required(input.method,40),reference=clean(input.reference||'',160);if(!['تحويل بنكي','نقدي','بطاقة','أخرى'].includes(method))fail('طريقة الدفع غير صحيحة');
 const prior=await database.prepare('SELECT * FROM invoice_payments WHERE id=?').bind(id).first();if(prior){if(prior.invoice_id!==invoiceId||prior.amount_cents!==amount)fail('معرف العملية مستخدم لدفعة أخرى',409);return json({ok:true,duplicate:true});}
 const result=await database.prepare('INSERT INTO invoice_payments (id,invoice_id,amount_cents,date,method,reference,created,by) SELECT ?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM supplier_invoices i WHERE i.id=? AND i.total_cents-COALESCE((SELECT SUM(amount_cents) FROM invoice_payments p WHERE p.invoice_id=i.id),0)>=?) ON CONFLICT(id) DO NOTHING').bind(id,invoiceId,amount,date,method,reference,now,a.name,invoiceId,amount).run();if(result.meta.changes!==1)fail('الدفعة تتجاوز المبلغ المتبقي أو تم تحديث الفاتورة. حدّث البيانات',409);return json({ok:true},201);
 }
 if(input.op==='stock'){
 const siteId=required(input.siteId,80),name=required(input.name,160),spec=clean(input.spec||'',500),unit=required(input.unit,40),qty=num(input.qty);if(qty<=0)fail('أدخل كمية أكبر من صفر');if(!['in','out'].includes(input.kind))fail('نوع الحركة غير صحيح');const kind=input.kind,date=day(input.date),note=required(input.note,1000),key=stockKey(siteId,name,spec,unit);
 const prior=await database.prepare('SELECT * FROM stock_moves WHERE id=?').bind(id).first();if(prior){if(prior.item_key!==key||prior.qty!==qty||prior.kind!==kind)fail('معرف العملية مستخدم لحركة أخرى',409);return json({ok:true,duplicate:true});}const site=await database.prepare("SELECT id FROM accounts WHERE id=? AND role='site'").bind(siteId).first();if(!site)fail('الموقع غير موجود');
 // One SQL statement checks the current receipt balance and concurrent movements.
 const result=await database.prepare("INSERT INTO stock_moves (id,site_id,item_key,name,spec,unit,qty,kind,date,note,created,by) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE ?='in' OR COALESCE((SELECT SUM(CAST(json_extract(j.value,'$.received') AS REAL)) FROM requests r,json_each(r.data,'$.items') j WHERE r.state IN ('approved','ordered','partial','received') AND r.site_id=? AND TRIM(json_extract(j.value,'$.name'))=? AND TRIM(COALESCE(json_extract(j.value,'$.spec'),''))=? AND TRIM(json_extract(j.value,'$.unit'))=?),0)+COALESCE((SELECT SUM(CASE WHEN kind='in' THEN qty ELSE -qty END) FROM stock_moves WHERE item_key=?),0)>=? ON CONFLICT(id) DO NOTHING").bind(id,siteId,key,name,spec,unit,qty,kind,date,note,now,a.name,kind,siteId,name,spec,unit,key,qty).run();if(result.meta.changes!==1)fail('الكمية المطلوبة للصرف أكبر من الرصيد المتاح. حدّث المخزون',409);return json({ok:true},201);
 }
 fail('إجراء غير صحيح');}catch(e){return error(e);}}
 return {GET,POST};
}
