import {can} from './permissions.mjs';
import {fail,required} from './purchase-domain.mjs';
export const MAX_INVOICE_SIZE=3*1024*1024;
export function fileAccess(user,request){const own=user.role==='site'&&request.site_id===user.id;return {read:user.role==='admin',upload:user.role==='admin'};}
function imageType(bytes){if(bytes.length<12)return null;if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)return {mime:'image/jpeg',ext:'jpg'};if([137,80,78,71,13,10,26,10].every((b,i)=>bytes[i]===b))return {mime:'image/png',ext:'png'};if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')return {mime:'image/webp',ext:'webp'};return null;}
const uuid=value=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value);
const safe=row=>({id:row.id,requestId:row.request_id,filename:row.filename,mime:row.mime,size:row.size,created:row.created,invoiceId:row.invoice_id||''});
const headers={'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'};
const json=(data,status=200)=>Response.json(data,{status,headers});
const error=e=>json({error:e.status?e.message:'تعذر حفظ أو تحميل صورة الفاتورة'},e.status||500);
export function createInvoiceHandlers({database,bucket,account}){
 async function requestFor(user,id,write=false){if(!uuid(id))fail('معرف الطلب غير صحيح');const request=await database.prepare('SELECT id,site_id FROM requests WHERE id=?').bind(id).first();if(!request)fail('الطلب غير موجود',404);const access=fileAccess(user,request);if(!(write?access.upload:access.read))fail('لا تملك صلاحية صور فاتورة هذا الطلب',403);return request;}
 async function GET(request){try{
  const user=await account(request);const url=new URL(request.url);const id=url.searchParams.get('id');
  if(id){if(!uuid(id))fail('معرف الصورة غير صحيح');const row=await database.prepare('SELECT * FROM invoice_files WHERE id=?').bind(id).first();if(!row)fail('الصورة غير موجودة',404);await requestFor(user,row.request_id);if(!bucket)fail('حفظ الصور غير متاح حاليًا',503);const object=await bucket.get(row.blob_key);if(!object)fail('تعذر العثور على الصورة المحفوظة',404);const mode=url.searchParams.get('download')==='1'?'attachment':'inline';return new Response(object.body,{headers:{...headers,'Content-Type':row.mime,'Content-Length':String(row.size),'Content-Disposition':mode+"; filename=\"invoice."+(row.mime==='image/png'?'png':row.mime==='image/webp'?'webp':'jpg')+"\"; filename*=UTF-8''"+encodeURIComponent(row.filename),'Content-Security-Policy':"default-src 'none'; sandbox",'Cross-Origin-Resource-Policy':'same-origin'}});}
  const requestId=url.searchParams.get('requestId');await requestFor(user,requestId);const invoiceId=url.searchParams.get('invoiceId')||'';if(invoiceId){const invoice=await database.prepare('SELECT request_id FROM supplier_invoices WHERE id=?').bind(invoiceId).first();if(!invoice||invoice.request_id!==requestId)fail('الفاتورة غير موجودة',404);}const rows=(await database.prepare('SELECT * FROM invoice_files WHERE request_id=?'+(invoiceId?' AND invoice_id=?':'')+' ORDER BY created DESC,id').bind(...(invoiceId?[requestId,invoiceId]:[requestId])).all()).results;return json({files:rows.map(safe)});
 }catch(e){return error(e);}}
 async function POST(request){try{
  const origin=request.headers.get('Origin');if(origin!==new URL(request.url).origin)fail('مصدر الطلب غير صحيح',403);const user=await account(request);if(user.role!=='admin')fail('رفع صور الفواتير متاح للمدير فقط',403);if(!bucket)fail('حفظ الصور غير متاح حاليًا',503);
  if(!request.headers.get('Content-Type')?.startsWith('multipart/form-data'))fail('ارفع الصورة من نموذج الفاتورة');const maxBody=MAX_INVOICE_SIZE+65536;if(Number(request.headers.get('Content-Length'))>maxBody)fail('حجم الصورة يجب ألا يتجاوز 3 ميجابايت',413);
  const reader=request.body?.getReader();if(!reader)fail('اختر صورة الفاتورة');let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maxBody){await reader.cancel();fail('حجم الصورة يجب ألا يتجاوز 3 ميجابايت',413);}chunks.push(value);}const bytes=new Uint8Array(size);let at=0;for(const part of chunks){bytes.set(part,at);at+=part.byteLength;}
  const form=await new Request(request.url,{method:'POST',headers:{'Content-Type':request.headers.get('Content-Type')},body:bytes}).formData();const requestId=form.get('requestId'),id=form.get('id');await requestFor(user,requestId,true);if(!uuid(id))fail('معرف الرفع غير صحيح');const invoiceId=form.get('invoiceId')||'';if(invoiceId){if(!uuid(invoiceId))fail('معرف الفاتورة غير صحيح');const invoice=await database.prepare('SELECT request_id FROM supplier_invoices WHERE id=?').bind(invoiceId).first();if(!invoice||invoice.request_id!==requestId)fail('الفاتورة لا تخص هذا الطلب',403);}
  const previous=await database.prepare('SELECT * FROM invoice_files WHERE id=?').bind(id).first();if(previous){if(previous.request_id!==requestId||previous.uploader!==user.id||previous.invoice_id!==invoiceId)fail('معرف الرفع مستخدم',409);return json({file:safe(previous),duplicate:true});}
  const file=form.get('file');if(!file||typeof file==='string'||typeof file.arrayBuffer!=='function'||!file.size)fail('اختر صورة الفاتورة');if(file.size>MAX_INVOICE_SIZE)fail('حجم الصورة يجب ألا يتجاوز 3 ميجابايت',413);const image=new Uint8Array(await file.arrayBuffer());const type=imageType(image);if(!type)fail('الصيغ المسموحة JPG وPNG وWEBP');
  const count=await database.prepare('SELECT COUNT(*) AS count FROM invoice_files WHERE request_id=?').bind(requestId).first();if(count.count>=20)fail('يمكن حفظ 20 صورة لكل طلب');
  const filename=required(file.name.replace(/[\u0000-\u001f\u007f/\\]/g,'_'),180);const key='invoices/'+requestId+'/'+crypto.randomUUID()+'.'+type.ext;const created=new Date().toISOString();await bucket.put(key,image,{httpMetadata:{contentType:type.mime}});
  const result=await database.prepare('INSERT INTO invoice_files (id,request_id,uploader,filename,mime,size,blob_key,created,invoice_id) SELECT ?,?,?,?,?,?,?,?,? WHERE (SELECT COUNT(*) FROM invoice_files WHERE request_id=?)<20 ON CONFLICT(id) DO NOTHING').bind(id,requestId,user.id,filename,type.mime,image.byteLength,key,created,invoiceId,requestId).run();
  if(result.meta.changes!==1){const existing=await database.prepare('SELECT * FROM invoice_files WHERE id=?').bind(id).first();await bucket.delete(key);if(existing&&existing.request_id===requestId&&existing.uploader===user.id&&existing.invoice_id===invoiceId)return json({file:safe(existing),duplicate:true});fail('لم تُحفظ الصورة؛ حدّث قائمة الفواتير وحاول مجددًا',409);}
  return json({file:{id,requestId,filename,mime:type.mime,size:image.byteLength,created,invoiceId}},201);
 }catch(e){return error(e);}}
 return {GET,POST};
}
